### ISSUE TITLE
beta-1.6 no longer uses keys.yaml

### ISSUE THREAD

**Issue by xorinox** [chia-dev/chia#1]
A fresh and working install of beta-1.6 doesn't use the keys.yaml any longer. The keys are not store in key store. Script need to be migrated to work with beta-1.6

python src/cmds/generate_plots_yaml_file.py -d /data/plots/disk1
Traceback (most recent call last):
  File "src/cmds/generate_plots_yaml_file.py", line 93, in <module>
    main()
  File "src/cmds/generate_plots_yaml_file.py", line 48, in main
    raise RuntimeError("Can not find keys.yaml.")
RuntimeError: Can not find keys.yaml.

**Comment by chia-dev** [comment]
Unfortunately it doesn't look like I can fix it in beta 1.6.
This is the response I got from the dev team:
regenerating file isn't currently possible.
there are changes that will make this possible In either beta 1.7 or 1.8, they key and all extra info will be part of the plot so you'll be able to regenerate this file by using just the plot
